version: '2'
services:
  feed-commissioner:
    build: .
    image: commissioner:latest
    container_name: commissioner.office.vm
    ports:
      - 8060:8060
    volumes:
    - .:/feed-commissioner 
